services:
  postgres:
    image: postgres:latest
    container_name: Employee
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: hasan
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

